### ISSUE TITLE
helpful-function doesn't show documentation

### ISSUE THREAD

**Issue by DamienCassou** [Wilfred/helpful#10]
When I type `M-x helpful-function RET shell-quote-argument`, I don't get the documentation of the function, except through it's source code. Is that expected? I would like a properly formatted documentation of each function so I can use helpful-function as a drop-in replacement for `C-h f`.

**Comment by DamienCassou** [comment]
Left is `helpful-function`, right is `describe-function`.

![screenshot](https://petton.fr/nextcloud/index.php/s/ruRlcFmfmpiDfVX/download)

**Comment by Wilfred** [comment]
Nope, that's not expected. Every function should show its documentation.

I can't actually reproduce this:

![shell_quote](https://user-images.githubusercontent.com/70800/29848449-86b2fb0a-8d18-11e7-84ec-57a77f0afb0e.png)

I'd initially guessed the issue was autoloading, but I'd expect to see 'this function has not been loaded' in the `*Help*` buffer if autoloading was the cause.

Are you seeing this with other functions?

**Comment by DamienCassou** [comment]
I cannot reproduce anymore. I will reopen when and if it comes back. Sorry for the noise.

**Comment by Wilfred** [comment]
I have an idea what happened here.

Earlier versions of Helpful only supported functions, so buffers only stored the symbol. Now that we support both variables and functions, there's a `helpful--callable-p` that needs to be set.

I'm guessing that you reloaded an existing results buffer after upgrading? That would have had `helpful--callable-p` as `nil`, so it would be trying to show the docstring of a variable called `shell-quote-argument`.
