### ISSUE TITLE
Syntax highlighting doesn't work for long functions

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#116]
At least that's what I think is happening. Specifically, syntax highlighting isn't getting applied to `describe-function-1` (a helper function used by `describe-function`). It's a very long function. If I delete a few lines and refresh, syntax highlighting gets applied. I haven't figured out exactly what the cutoff is.

**Comment by Wilfred** [comment]
This is intentional, see `helpful-max-highlight` and #107.

I'm open to suggestions if you think 5000 chars is a poor threshold, or it's possible that we could choose different thresholds for elisp and C snippets (or Rust if you're running Remacs).

That said, on Emacs 26.1, `describe-function-1` isn't long enough to hit that limit when I tried it.

**Comment by nickdrozd** [comment]
Ah, I didn't see that before. Changing that value to 10000 causes the function to highlight correctly. It didn't strike me as particularly slow, so maybe it's a C syntax issue, or maybe the threshold is just too low. `helpful` isn't performance-critical (unlike, say, `magit`), so I would prefer to err on the side of more information at the cost of some speed. (I don't know where the line should be exactly.)

In any case though, turning off syntax highlighting _feels_ like a bug when it happens, so what about adding some kind of message to indicate that?

**Comment by Wilfred** [comment]
Done :)
