### ISSUE TITLE
[Question] Suggested kbd choice for helpful-at-point

### ISSUE THREAD

**Issue by doolio** [Wilfred/helpful#173]
The README suggests the following:

`(global-set-key (kbd "C-c C-d") #'helpful-at-point)`

This clashes with `org-deadline`. Would it make more sense to replace `describe-symbol` with `helpful-at-point` so

`(global-set-key (kbd "C-h o") #'helpful-at-point)`

or would this be unwise? Thank you for your time and this package.

**Comment by Wilfred** [comment]
Hi @doolio! Thanks for using my package :)

I do think helpful should eventually allow you to use it for overriding the `describe-foo` commands, which is something we've discussed in #63. Note that the equivalent of `describe-symbol` is `helpful-symbol`.

I think being overridden by org-mode commands isn't too bad, because the symbol at point in an org-mode buffer is less likely to be an elisp symbol. I picked `C-c C-d` because it's similar to Slime (which uses `C-c C-d d` for `slime-describe-symbol`) and I didn't have any better ideas.

Since this is just a recommendation in the readme, I think it's OK. Hopefully users can see what they'd need to change if they want to use a different keybinding.
