### ISSUE TITLE
Helpful doesn't seem to respect display-buffer-alist (or I am doing something wrong?)

### ISSUE THREAD

**Issue by renbus** [Wilfred/helpful#346]
Hello,

If I click on a link in a Helpful buffer, or if I execute `helpful-callable`, or `helpful-variable` while an Helpful buffer is the active window, the new Helpful buffer will appear in the "other-window". If the Helpful window is the only window, it still launches itself in "other-window" (so it splits the screen). That makes using Helpful quite annoying.

I tried to prevent it from doing so with:

```
(add-to-list 'display-buffer-alist
             '((major-mode . helpful-mode)
              (display-buffer-reuse-window)
              (inhibit-same-window . nil)))
```

But it doesn't seem to prevent it from using the "other-window". Am I doing something wrong?

By the way, I set the helpful-max-buffers user option to 1, if that may explain anything.

**Comment by IceAsteroid** [comment]
@renbus, Hi!


Because the buffer names of helpful for different documents are different, `display-buffer-reuse-window` matches the existing same buffer name with the one that's gonna open. So you have to match the same mode instead.
 
It seems that `display-buffer-reuse-window` only work for buffers specified in regexps. You have to use `display-buffer-reuse-mode-window` to take effect for modes. So that you can do the following options:

You can specify `display-buffer-reuse-mode-window` or specify both `display-buffer-reuse-mode-window` & `display-buffer-reuse-window` in some other cases. 

Method 1:
```
  (add-to-list 'display-buffer-alist
               '((major-mode . helpful-mode)
                 (display-buffer-reuse-mode-window)
                 (inhibit-same-window . nil)))
```

Method 1.1: 
```
  (add-to-list 'display-buffer-alist
               '((major-mode . helpful-mode)
                 (display-buffer-reuse-window
                  display-buffer-reuse-mode-window)
                 (inhibit-same-window . nil)))
```

Method 2: Match buffer name instead for quicker display of the new helpful buffer(I presume, maybe not true)
```
  (add-to-list 'display-buffer-alist
               '("\\*helpful.*"
                 (display-buffer-reuse-window
                  display-buffer-reuse-mode-window)
                 (inhibit-same-window . nil)))
```

**Comment by IceAsteroid** [comment]
It seems that `display-buffer-reuse-window` matches the exact same name with existing live window and the one to open, so use `display-buffer-reuse-mode-window` or both.

**Comment by renbus** [comment]
Hello!

Thanks for your reply. Your methods, at least 1 and 1.1, both work, so that's great. Although, at first it wasn't working for me, but then I found out that setting the `helpful-max-buffers` to 1 was an issue. When I think about it, it makes sense. Probably that this setting was doing that the helpful buffer would first get killed, before opening a new one, so the display-buffer-alist rule wouldn't be able to re-use the same window.
