### ISSUE TITLE
Some formatting issues

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#83]
This shows up when calling `helpful-callable` on `query-replace-regexp`:

```
Use \<minibuffer-local-map>M-x next-history-element to pull the last incremental search regexp to the minibuffer
that reads REGEXP, or invoke replacements from
incremental search with a key sequence like C-M-s C-M-s C-M-%
to use its current search regexp as the regexp to replace.
```

(If it doesn't show up right on GitHub, the first line goes from `Use` through `minibuffer`, which is more than 100 characters long.)

Here is what `describe-function` has:

```
Use M-n to pull the last incremental search regexp to the minibuffer
that reads REGEXP, or invoke replacements from
incremental search with a key sequence like ‘C-M-s C-M-s C-M-%’
to use its current search regexp as the regexp to replace.
```

So this looks like some kind of formatting screw-up. That said, it would be interesting to see the name of the command in addition to the key (I had never heard of `next-history-element`).

***

As a separate issue, the pseudo-rounded quotes \``'`  show up unformatted:

```
In TO-STRING, `\&' or `\0' stands for whatever matched the whole of
REGEXP, and `\N' (where N is a digit) stands for whatever matched
the Nth `\(...\)' (1-based) in REGEXP.  The `\(...\)' groups are
counted from 1.
`\?' lets you edit the replacement text in the minibuffer
at the given position for each replacement.
```
I don't know if this is intended.

**Comment by Wilfred** [comment]
Thanks. The keymap issue should now be fixed.

I agree that it might be nice to show the command name as well as the keybinding, but that would spoil the line wrapping (the affected lines would get much longer). Ideally we'd avoid that.

Since you can press the button to see what the command is, I think this is somewhat discoverable, at least.

---

Regarding quotes, I'm trying to make Helpful show them as rarely as possible. I'd rather show something better formatted. If we can't show anything, I prefer showing ASCII `` ` `` and `'` rather than curly quotes, because that's probably what's in the docstring. I think being closer to the docstring helps inform the user how docstrings work.
