### ISSUE TITLE
Screwy output for anonymous function keybinding

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#97]
The anonymous function keybinding issues was fixed (c2870c3), but the
output for such keys is still a little screwy. I have <kbd>C-.</kbd>
bound to `other-window`, which "goes to the right", and <kbd>C-,</kbd>
bound to `(lambda nil (interactive) (other-window -1))`, which "goes
to the left".

Here is what `helpful-key` gives me for <kbd>C-,</kbd>:

```
This lambda is an interactive function without source code.

Function Signature
()

Key Bindings
global-map C-,
widget-global-map C-,

References
Could not find source file.

Find all references

Debugging
Disassemble Forget

Source Code
;; Source file is unknown
(lambda nil (interactive) (other-window -1))
```

It says that the function is "without source code", which is
manifestly false, as the source code is given right there at the
bottom. It would also be nice to see the source file if that's
possible (I don't think the would be possible if the key were bound to
an anonymous function on the fly, but that isn't the case here).

**Comment by Wilfred** [comment]
OK, I've clarified the wording, so you now get this:

```
This lambda is an interactive function without a source file.

Function Signature
()

Key Bindings
global-map <f1>
widget-global-map <f1>

References
Could not find source file.

Find all references

Debugging
Disassemble Forget

Source Code
;; Source file is unknown, showing raw function object.
(lambda nil
  (interactive)
  (if nil (progn (message "never called")))
  (message "hello"))
```

This was from the following in my init.el:

```emacs-lisp
(global-set-key (kbd "<f1>")
                (lambda ()
                  (interactive)
                  ;; comment.
                  (when nil
                    (message "never called"))
                  (message "hello")))
```

You can see that when we show the raw function object the code has been macro-expanded and has no comments. I've clarified the wording to reflect that this is the raw object, and to say 'no source file' rather than 'no source code'.

I'm afraid I'm not aware of any way of getting the source code back from Emacs from just a function object, so I think this is the best we can do.
